apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: logicgod007/adsremedy:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              
            limits:
              cpu: "600m"
              
